### ISSUE TITLE
disable map interface

### ISSUE THREAD

**Issue by mleo1** [MStr3am/NEMO#104]
I dunno if error or not, 2013-08-07, cannot disable the map interface, "failed in step 1" it says

**Comment by MStr3am** [comment]
oO I am not seeing the error.

**Comment by MStr3am** [comment]
try it now.

**Comment by MStr3am** [comment]
Please reopen the issue if it is still there.

**Comment by mleo1** [comment]
works now, xD

**Comment by mleo1** [comment]
hello can the map button be disabled too?
