### ISSUE TITLE
Public Chat bug on 2015-10-29aRagexeRE

### ISSUE THREAD

**Issue by ragnaworld** [MStr3am/NEMO#107]
Last letter on public chat is missing for other player's point of view
![capture](https://cloud.githubusercontent.com/assets/16416740/12206477/052129a4-b5f6-11e5-8652-504489612ff9.PNG)

http://postimg.org/image/gv3ab8cih/

**Comment by Jedzkie** [comment]
This is source problem, not client side.

**Comment by MStr3am** [comment]
Figured as much. Closing this issue.
