### ISSUE TITLE
Enable Custom Jobs Patch issue on 2015-09-16

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#108]
Without Enable Custom Jobs Patch: The client can access the Server Service Select without any problems.
With Enable Custom Jobs Patch: The client crashes when you access the Server Service Select.

**Comment by Angelmelody** [comment]
I can confirm this problem :)

**Comment by mimishi** [comment]
any news with this problem :(

**Comment by MStr3am** [comment]
Fixed.
