### ISSUE TITLE
Restore Login Window Bug

### ISSUE THREAD

**Issue by Jedzkie** [MStr3am/NEMO#11]
Hi Neo! I think this issue is based on Restore Login Window. I Noticed it on 2013-08-07 and 2013-12-30 Ragexe Clients

How to reproduce:

- Run the client.
- Then click 'Close'
- You will see that the Interface will remove, instead of showing 'Do you want to exit?'.

Kindly check this. Thank you!

**Comment by MStr3am** [comment]
i believe you are talking about service selection screen.

The exit button on Login Window works fine for me. 
The cancel buttons on server selection and character selection screens either ask to quit the game or cancel to login screen if the patch is used.
other than that there are no other buttons cancel/quit type buttons in any other windows before map loading.

If you only have 1 connection specified in Clientinfo,xml you can choose to skip the service selection screen (the patch is working now). I need time to check where the cancel button goes to but its not on priority right now.
