### ISSUE TITLE
More additions to the Hide button diff

### ISSUE THREAD

**Issue by EPuncker** [MStr3am/NEMO#110]
We already got "Hide BG, bank, etc" button options, I'd like to suggest the addition of the following as well:
- achievement
- rodex
- rec
- map
- quest

**Comment by Jedzkie** [comment]
@EPuncker if the booking button is disabled, try to use /booking if it still showing.

**Comment by EPuncker** [comment]
I know xD my point is just to hide the buttons from the interface

![screenragnaflux000](https://cloud.githubusercontent.com/assets/4684880/12342147/e55383ba-bb0e-11e5-9db5-3e054e8c1469.jpg)

**Comment by MStr3am** [comment]
rodex & achievement hiding is already there. rest i will add .

**Comment by MStr3am** [comment]
Added the rest.

**Comment by EPuncker** [comment]
thanks, is it just me or I can't seem to find the rodex hide option anywhere in nemo? using 2015-05-13aRagexe by the way

**Comment by MStr3am** [comment]
check now.

**Comment by EPuncker** [comment]
quest button is still showing up even after that, others are working well

**Comment by MStr3am** [comment]
ok looks like it matched another location. Fixed now.

**Comment by Jedzkie** [comment]
@MStr3am i can still access booking using /booking command, maybe you can disable it also?

**Comment by Jedzkie** [comment]
If quest also disabled maybe you can disable the alt + U command too.

**Comment by EPuncker** [comment]
I guess the purpose of the hide button is just to hide and not to disable the entire feature xD and @MStr3am it is working 100% now, thanks!
