### ISSUE TITLE
Enable Proxy Support Patch issue on 2015-05-13a Client

### ISSUE THREAD

**Issue by Mintmoon** [MStr3am/NEMO#113]
At NEMO2.6(2016-01-15) to work fine when you enable the "Enable Proxy Support Patch" to 2014-10-22b Client, but it does not seem to be working and to apply to the 2015-05-13a Client.
Sorry Google Translate...:(

**Comment by MStr3am** [comment]
Both clients are getting patched same way can you elaborate what exact issue you are facing with 2015 client.

**Comment by MStr3am** [comment]
Closing this. since there is no response for 2 months. If the issue persists please reopen with details.
