### ISSUE TITLE
2015-10-29aRagexeRE Cancel to Login Window

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#115]
Cancel to Login Window is not working on 2015-10-29aRagexeRE or no Cancel button

![new char select](https://cloud.githubusercontent.com/assets/4656578/12535004/5d223110-c2ae-11e5-8db3-8ec577350f00.jpg)

**Comment by Jedzkie** [comment]
press the 'x' button on the upper right corner of the gui.

**Comment by MStr3am** [comment]
From what I can tell they are now using a different function for making the select character window. And the cancel button is longer getting created. 
Right now only way is to make the the X button to respond similar to cancel button. I am working on that.

**Comment by MStr3am** [comment]
Fixed.

**Comment by M45T3Ryu** [comment]
this doesnt work with 2015 09 14
