### ISSUE TITLE
Use Custom Aura Limits Issue

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#117]
After applying "Use Custom Aura Limits" patch my client suddenly crashes.

Client: 2015-09-16aRagexe

**Comment by AetherHaziel** [comment]
Same with 2013-08-07.

**Comment by mrlongshen** [comment]
Bump. Happen in same situation.
[http://herc.ws/board/topic/12140-custom-aura-crash-upon-login-ingame/](url)

**Comment by MStr3am** [comment]
Fixed. but Pre-2013 client still has dependency on the aura type based on job. Need to figure that out later.

**Comment by mrlongshen** [comment]
Thanks its fix now :))

**Comment by AetherHaziel** [comment]
For the hard work on all those updates, thank you, NeoMind, thank you.

**Comment by mrlongshen** [comment]
Nemo, the aura show in own self only. I cant see other aura.

// Maximum allowed 'level' value that can be sent in unit packets.
// Use together with the aura_lv setting to tell when exactly to show the
aura.
// NOTE: You also need to adjust the client if you want this to work.
// NOTE: Default is 99. Values above 127 will probably behave incorrectly.
// NOTE: If you don't know what this does, don't change it!!!
max_lv: 99

// Level required to display an aura.
// NOTE: This assumes that sending max_lv to the client will display the
aura.
// NOTE: aura_lv must not be less than max_lv.
// Example: If max_lv is 99 and aura_lv is 150, characters with level 99~149
//          will be sent as being all level 98, and only characters with
level
//          150 or more will be reported as having level 99 and show an
aura.
aura_lv: 255

My setting correct right?

**Comment by OmarMohamedHasan** [comment]
Hello , I see I get crash every time I use ( Use Custom Aura Limits Issue ) 
And I can see too that the bug marked as completed 
May I know if there's a new patch or something for this or not 
And need to know what's the numbers after the levels?
  99-149 => 1,
  150-159 => 2,
  160-255 => 3,
The 1 , 2 and 3 numbers?!
