### ISSUE TITLE
2015-10-29aRagexeRE translateclient.txt

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#118]
BC D2 C8 AF BC FA BB E7 is not working on >= 2015-10-29 client

New hex:
F: BC D2 C8 AF BB E7
R: 'Summoner'

**Comment by MStr3am** [comment]
You can modify it yourself and create a pull request :P

**Comment by kyeme** [comment]
Ok, thanks.

@Jedzkie can you make a pull request bro? Thank you!

**Comment by MStr3am** [comment]
Fixed.
