### ISSUE TITLE
Palettes on hairstyles 100+ error out randomly

### ISSUE THREAD

**Issue by ElysiumTan** [MStr3am/NEMO#12]
Every hairstyle 100 and above will cause the client to crash if it happens to be using a palette.  With certain conditions, I can sometimes get it to work to about hairstyle 101 or so, but anything beyond that makes the client freeze and error out with no error message.

http://i.imgur.com/ZZUHnoU.png

**Comment by EPuncker** [comment]
is it still happening?

**Comment by MStr3am** [comment]
is it happening for you? i didnt get time to check for the 100+ ids yet.

**Comment by EPuncker** [comment]
for me don't since I use only official style, but I plan to add custom as well but not that many lol

**Comment by ElysiumTan** [comment]
Still happens, ended up restricting hairstyles to 99 to outright avoid this bug

**Comment by MStr3am** [comment]
Which client date is it happening on or is it there for every client. 
My guess its probably got something to do with the stack allocation (since the original limit has only 2 digits maybe the extra chars when it becomes 3+ digits is making the string invalid - no gap for \0 at the end).

**Comment by MStr3am** [comment]
Is there a hairstyle pack that has 100+ hairstyles so I can test for this?

**Comment by MStr3am** [comment]
I am going to be checking in an updated version of the Enable 64k Hairstyle patch today. Please check with that. 
I saw a potential issue that leads to an invalid memory access when trying to get any hairstyle > the original limit. Maybe this issue is also from that. Its a miracle that it didn't crash sooner.

**Comment by MStr3am** [comment]
Please reopen the issue if the problem still persists

**Comment by RagnarokNova** [comment]
Hey @MStr3am , I've been trying to ready up a brand new client (2016-12-28aRagexeRE.exe) but I believe I'm getting those memory access errors. When I get to character select, 50% of the time my client crashes if any of my characters have a hairstyle > the original limit. The other 50% of the time my client works just fine. Have you had any luck with this issue? I'd be happy to send you the client if you need it.
