### ISSUE TITLE
Custom 3D NPC models crash

### ISSUE THREAD

**Issue by Everade** [MStr3am/NEMO#123]
Hey there

I've recently updated to the client:
2015-06-19aRagexe

I have used the latest NEMO repo, and diffed the Custom 3D Bones.
Client side is everything in place (lua files and the 3d models itself)
granny2.dll should be fine as well.

So i'm betting on an issue on the diff itself.

Looking forward to a reply,

Cheers

**Comment by Everade** [comment]
Forgot to mention:

The client crashes on Custom moving 3D Models being placed on a map as **NPCs**.

**Comment by Everade** [comment]
Any comment on this?
Really looking forward to an investigation/update/comment.

**Comment by chatchanunn** [comment]
I have this problem too. 
This diff cannot read 3D Bones that index over 9.

**Comment by MStr3am** [comment]
Fixed.

**Comment by Everade** [comment]
Awesome, works perfect, thank you!
