### ISSUE TITLE
2012-04-10 Custom Jobs and Restore Login Window problems

### ISSUE THREAD

**Issue by HeroGarr** [MStr3am/NEMO#124]
Good time of day.

Today I have to report 2 problems:

First, if I patch client with Enable Custom Jobs from latest NEMO, client crashes on login screen. However, with patch from 0d9ee59ee88b28b800fe7d343829384e0a5b89fc it works just fine.

Second, with restored login window batch there's a small issue (not sure if someone even noticed it before). If you log out from one account, and *without* getting back to server select try to login another account it will fail. Here are the 2 caught packets:

64 00 
19 00 00 00 
54 65 73 74 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
54 65 73 74 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
10

64 00 
19 00 00 00 
54 65 73 74 00 6E 6E FF 4C 4C 4C FF 20 63 3E 3F 25 75 32 3F 20 63 3E 3F 
54 65 73 74 00 11 06 C2 28 3E 08 42 32 80 4F C1 CC DD D3 C1 03 02 00 01 
0E

As you can see, 2nd one contains garbage data, even if after null terminator >.< Guess it can be passed as server-side problem as well, but nonetheless.

And thank you for your hard work, it's way too awesome /no1

**Comment by AetherHaziel** [comment]
I don't know about Restore Login Window, but, Custom Jobs, the old patch worked, but I discovered it crashes the client when you try to use cash mounts.

The latest patch doesn't work at all, it crashes just after opening the Hexed.
NeoMind, I loved your custom job patch, please, if you can, fix it so I can continue the custom job creation proccess!

Thank you.

**Comment by HeroGarr** [comment]
@AetherHaziel 
If it crashes on cash mounts, then you went 1 commit on patch too far. I reported it in issue #52 and it indeed was fixed on 2012-04-10 ^_^

**Comment by AetherHaziel** [comment]
Still, on 2013-08-07, the old patch crashes on cashmounts, and the new one, just crashes after the client opens. Tested diff per diff.

**Comment by MStr3am** [comment]
Custom Job issue is fixed. About the Restore Login Window problem do you mean when you are changing character? Because I don't see how you can change account without going back to the login screen unless you meant login via a second client.

**Comment by HeroGarr** [comment]
No, I mean when you get back to the server login screen, the one with login/password prompt. If you don't go back to server select it'd start sending login/pass with garbage data.

**Comment by MStr3am** [comment]
Odd works fine for me. Here is what I did.

Logged in with First account -> Selected a character and entered map -> Returned to Character Select -> Pressed cancel to return to Login Screen -> Logged in with Second account -> Selected character and Entered map.
No issues at any stage,

**Comment by HeroGarr** [comment]
Hmm. Let me pull and try again. For the time being my patchlist:
[Patch.txt](https://github.com/MStr3am/NEMO/files/174387/Patch.txt)

**Comment by MStr3am** [comment]
Which client date

**Comment by HeroGarr** [comment]
2012-04-10

**Comment by MStr3am** [comment]
I hope you meant the RE client. Tried the same set of patches (except for the Packet Keys i used the default ones). Still works fine.

https://www.mediafire.com/?9pnx0ngklog6tef this is my patched exe

**Comment by HeroGarr** [comment]
Well, that's odd. Guess it can be closed then, as the job patch works, and latter issue is minor to begin with. Thanks a ton for your hard work <3
