### ISSUE TITLE
Ragnarok Icon

### ISSUE THREAD

**Issue by ignizh** [MStr3am/NEMO#126]
RO Icon Patch don't work properly, still displays the default exe icon.

**Comment by MStr3am** [comment]
Which icon did you use and which client date is causing the problem.

**Comment by ignizh** [comment]
2014-10-22bRagexe
Patch: "Use Ragnarok Icon"

Thanks in advance.

**Comment by MStr3am** [comment]
I am seeing the RO Icon fine for that client date. If you are using the Use Custom Icon patch then show me which icon you used.

**Comment by MStr3am** [comment]
Closing this since there is no response for 2 months. Reopen ticket with details if issue persists.
