### ISSUE TITLE
[Request]unicode string support for window title 

### ISSUE THREAD

**Issue by Angelmelody** [MStr3am/NEMO#130]
Hi @MStr3am , 
I'd like to request the custom title string patch  to support unicode string,
Coz I had tried to translate title string to Chinese but it will become gibberish
so hoping dev can add it TIA

**Comment by CairoLee** [comment]
### Confirm this.

#### if custom an english windows title in NEMO:

![qq20160323-0](https://cloud.githubusercontent.com/assets/4458917/13974378/2adaff32-f0e6-11e5-9bb8-5d1a0010977b.png)

##### it's work

![qq20160323-1](https://cloud.githubusercontent.com/assets/4458917/13974387/3a4b558e-f0e6-11e5-867a-1a8394207db9.png)

#### But if use Chinese or Japanese to set windows title:

![qq20160323-2](https://cloud.githubusercontent.com/assets/4458917/13974402/63581c6e-f0e6-11e5-9f2f-1cfbb3537648.png)

##### then it's will become gibberish

![qq20160323-3](https://cloud.githubusercontent.com/assets/4458917/13974414/73459390-f0e6-11e5-8bb5-93763deb0f21.png)

**Comment by MStr3am** [comment]
The client's window is created to support ASCII not Unicode (see CreateWindowExA and RegisterClassA functions). I tried to change them to W functions but title still did not get detected as Unicode string (Probably lot more steps involved). Plus it ended up causing other problems as well.

So I am rejecting this.
