### ISSUE TITLE
2012-04-10RE

### ISSUE THREAD

**Issue by Litro** [MStr3am/NEMO#14]
Crashes Patch on 2012-04-10RE
- Increase Attack Display
- Increase Headgear ViewID

And the langtype on clientinfo.xml if i used 0 = Patch Use Custom Font will Fail and if Used 6 as langtype Selected login background will come as Black Login Screen

**Comment by MStr3am** [comment]
Attack Display should be resolved now. Headgear View ID i will test it with a headgear but as is its not crashing.
The others i havent heard of till now but i will check them.

**Comment by MStr3am** [comment]
didnt see the custom font issue rest are done.
