### ISSUE TITLE
Recommended patches

### ISSUE THREAD

**Issue by dastgir** [MStr3am/NEMO#141]
Maybe ads "Custom itemInfo name" into recommended patch?
Since having default name would make it overwrite with every kro updates...

**Comment by MStr3am** [comment]
hmm true everyone is probably gonna have one or two custom items atleast. I'll add it

**Comment by dastgir** [comment]
It's not just for custom :p everybody is gonna have translated itemInfo too

**Comment by MStr3am** [comment]
oh yea :D . Anyways done.
