### ISSUE TITLE
[Bug] In client Register Button -> Client crashes

### ISSUE THREAD

**Issue by Ouvertuere** [MStr3am/NEMO#142]
After clicking the "register" button in the left corner of the login box the following happens:

- Client **crashes** respectively stops working

- The desired website (which is defined in the clientinfo.xml) pops up.

Client date: 2014-02-05bRagexe
Diffed with NEMO Patcher

The diffs I choose: [click me](http://upaste.me/r/08f7262213a6843b9)

**Comment by joelolopez** [comment]
did u include registerweb tags in your clientinfo?

**Comment by MStr3am** [comment]
I have added a new patch "Show Register Button". Try using that it should fix the problem. Patch will show the button for all langtypes and close the client while opening URL from <registrationweb> tag
