### ISSUE TITLE
MAIL WINDOWS NO WORK IN CLIENTS 2015

### ISSUE THREAD

**Issue by darknessfmy** [MStr3am/NEMO#146]
Not working the Mail windows, this is a error of nemo patchet (i use 2015-11-04)

**Comment by Everade** [comment]
RoDex is the new mail system. (rAthena does not yet support it, don't know about hercules)
The old one is deprecated and has been officialy removed by Gravity.

**Comment by MStr3am** [comment]
Closing since issue is not related to NEMO.
