### ISSUE TITLE
Change Walk To Delay issue

### ISSUE THREAD

**Issue by Everade** [MStr3am/NEMO#152]
All settings below 100 (especially the default 40) or the Disable Walk To Delay
**causes you to walk every time even if you use a skill which is on cooldown.**

This is very very annoying for all warlock or similiar classes with floor skills.
You can simply test it using Comet.
During it's cooldown, just spam comet around yourself, you will walk each time even if the skill fails (is still in cooldown)

I've tested myself through...
Starting at >=100 Walk To Delay it's getting masively better.
At 100 you may get a few rare walkings.
150 seems to be about the best setting to not get any false walkings anymore, while maintaining better walk delays.

However of course it would be great to have 0 delay for walking, but still shouldn't trigger for skills on cooldown or other things.

**Comment by LiamKarlMitchell** [comment]
Agree, sorry I did not notice that as I normally hold shift when casting skills and my click is about 30~

Made something to test the mouse down/up speed https://codepen.io/LiamKarlMitchell/pen/XapNMN

Referencing issue that brought this too my attention and caused me to come here to search.
https://github.com/rathena/rathena/issues/2046

**Comment by LiamKarlMitchell** [comment]
https://github.com/MStr3am/NEMO/pull/172
