### ISSUE TITLE
Can't download 2010 clients

### ISSUE THREAD

**Issue by AtomixRO** [MStr3am/NEMO#178]
Hello,

All I get is the following:

Error mirror1: HTTP Error 521: Origin Down
Error mirror2: HTTP Error 404: Not Found
Error mirror3: HTTP Error 403: Forbidden

Would it be possible to fix the download links please?

Thank you

**Comment by 4144** [comment]
look like you reporting in wrong repository.

current nemo repository is here https://gitlab.com/4144/Nemo/-/issues

**Comment by AtomixRO** [comment]
Oops, thank you
