### ISSUE TITLE
Custom Job support

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#19]
In PCIds.lub
Missing "PCJobTable." in Baby_List. Thats the reason why the baby classes arent view like baby but like an normal class.

In PCPaths.lub
Wrong path
[PCJobTable.JT_ASSASSIN_B] = PCJobTable.JT_HUNTER,

It should be..
[PCJobTable.JT_ASSASSIN_B] = PCJobTable.JT_ASSASSIN,

**Comment by MStr3am** [comment]
well i have cleaned up the patches now and also fixed the items you mentioned. Let me know if you see anything else. Thanks for the heads up.
