### ISSUE TITLE
PacketEncryptionKeys.qs

### ISSUE THREAD

**Issue by nanakiwurtz** [MStr3am/NEMO#20]
File Name: https://github.com/MStr3am/NEMO/blob/master/Patches/PacketEncryptionKeys.qs
Line 26-41 is not needed, you can actually use same keys on all three to make it to work functionally, try to use 0x87654321 on all 3 keys, it won't break the function... :pizza: 
(But feel free if you want to reject this suggestion as well)

**Comment by MStr3am** [comment]
yea i get that. but the reason for the check is to avoid confusion when someone tries to change all 3 keys at same time for clients with shared keys.
