### ISSUE TITLE
Increase Attack Display

### ISSUE THREAD

**Issue by AceMeister** [MStr3am/NEMO#21]
Hi Neo,

My client crashes each time i select the increase attack display button and cast a skill.

2012-04-10 client being used.

**Comment by MStr3am** [comment]
odd let me check it. Ragexe or RagRE?

**Comment by AceMeister** [comment]
RagexeRE

and the one by judas

http://supportmii.com/ro1/Clients/ClientSideArea/2012_04_10/

the _S

not the patched one.

**Comment by MStr3am** [comment]
check now the patch had 1 small bug when patching pre-2013 clients.

**Comment by AceMeister** [comment]
Hi Nemo, excellent, the damage shows now but the heal shows 0999 anything beyond 32567 heal :/

**Comment by AceMeister** [comment]
Same for the SP , thanks for the great work btw!

**Comment by AceMeister** [comment]
Hope these images will help identify the issue :)

Damage Received 0094
http://i58.tinypic.com/k96wr8.jpg

Damage Dealt 0004
http://i57.tinypic.com/2rxa2oo.jpg

Damage Dealt 0794
http://i58.tinypic.com/8x6l9d.jpg

Heal 0328
http://i57.tinypic.com/11qpog6.jpg

There's also issues with the SP, sometimes sp regen at like 0997 @_@

**Comment by MStr3am** [comment]
hmm odd

**Comment by MStr3am** [comment]
The zero insertion issue has been fixed.
