### ISSUE TITLE
Client Issues after Patching with Nemo

### ISSUE THREAD

**Issue by AceMeister** [MStr3am/NEMO#22]
1. After patching the client with nemo, i always get korean symbols for the skill tree as well as location in the character window.

e.g. sonic blow will become !Σ∞¶ etc etc.

Is there a fix for this? Thank you!

2. After patching the client with nemo, (adding in the packet keys into the client), when i go to prontera, it always gets stuck at 3% even after applying Tokei's newprontera.grf

Using 2012-04-10 client. Thank you!

**Comment by MStr3am** [comment]
the skill tree is handled by lua files, patching wont have any influence on that, check ur skilltree lua files.

well i havent tried out the new prontera in old client, which exe is that Ragexe or RagRE

**Comment by AceMeister** [comment]
RagexeRE

**Comment by MStr3am** [comment]
The new prontera was never really meant to work with old clients in the first place. 
From what i heard, Tokei's GRF does work (atleast for some people) but even then some portions of the map still errors them.

Its not related to NEMO its just the map's design. Can't do much about it sadly.
