### ISSUE TITLE
1st login screen error

### ISSUE THREAD

**Issue by ernestfegarido** [MStr3am/NEMO#23]
sometimes the client cant find my 1st login background. but i have my 1st login backround in my grf.

**Comment by MStr3am** [comment]
thats weird. which client and what all patches are you using.

**Comment by ernestfegarido** [comment]
2014-04-16aRagexe my custom patch is 1st login backgorund and the rest is recommended patch :)

**Comment by EPuncker** [comment]
I just got the same thing here, client 2014-10-22b (or whatever the one yommy posted lol)

list of patches I'm using http://pastebin.com/UUPi9xPQ

**Comment by MStr3am** [comment]
odd all that patch is doing is making both background filenames to point to same file. which langtype are you using could be something from that.

**Comment by EPuncker** [comment]
langtype 12 here

**Comment by MStr3am** [comment]
fixed.
