### ISSUE TITLE
error client 2014-04-16aRagexe_patched

### ISSUE THREAD

**Issue by ernestfegarido** [MStr3am/NEMO#24]
![adasdas](https://cloud.githubusercontent.com/assets/4651777/7348535/f6fbd36e-ed24-11e4-9979-365ec7c57c1b.PNG)

**Comment by ernestfegarido** [comment]
when i patch my client with the new version of nemo i got that error :(

**Comment by MStr3am** [comment]
that is from the swear filter patch. I have fixed it in my local. Will push the changes in today.
