### ISSUE TITLE
CancelToLoginWindow issue

### ISSUE THREAD

**Issue by reigneil** [MStr3am/NEMO#28]
@MStr3am i think this patch is broken., not working on 2014-06-13aRagexe to be exact.

**Comment by EPuncker** [comment]
mind trying with 2014-10-20 (or 22) to see if it is working?

**Comment by reigneil** [comment]
well i don't have that client to test but what just i do right now to make it work again is to rollback the changes done for CancelToLoginWindow.qs and it is working again. same thing that i did at DisableSwearFilter.qs bug.

**Comment by MStr3am** [comment]
SwearFilter should be working will check the Cancel to Login window one.

**Comment by MStr3am** [comment]
This has been fixed. Will push the changes in today.
