### ISSUE TITLE
Shared palettes diff reading from wrong location

### ISSUE THREAD

**Issue by EPuncker** [MStr3am/NEMO#30]
actually applying the patch (both or either one) makes client to read the following:

data\palette\head_example.pal
data\palette\body_example.pal

I suggest that we keep using the official paths:

data\palette\¸Ó¸®\head_example.pal
data\palette\¸ö\body_example.pal

**Comment by MStr3am** [comment]
hmm yea saw that now. will fix that

**Comment by MStr3am** [comment]
done.
