### ISSUE TITLE
Disable hallucination wavy screen patch

### ISSUE THREAD

**Issue by EPuncker** [MStr3am/NEMO#31]
maybe this patch needs a rename since there is quite long time that gravity changed the hallucination behavior, it doesn't lags/waves the screen anymore, just make it upside-down

**Comment by MStr3am** [comment]
hmm but does the patch remove the upside-down effect or is that still there despite the patch.

**Comment by EPuncker** [comment]
I don't know, got no intention in using this patch (well I guess no one uses it anymore in new clients lol), we used to use it just because of the lag that the wavy screen effect gave, the upside-down effect is kinda funny and fine to have :P maybe make the remove wavy patch to be applicable only in old clients

**Comment by MStr3am** [comment]
any idea around when they changed it :)

**Comment by EPuncker** [comment]
sure:
https://rathena.org/board/topic/63466-05162012-kro-maintenance/

**Comment by zackdreaver** [comment]
add "Remove Inverted Screen effect" ?

**Comment by MStr3am** [comment]
disabled for 20121605+ clients. Maybe check on the Inverted Screen effect later

**Comment by dastgir** [comment]
20120516 -_-

**Comment by zackdreaver** [comment]
hue hue

**Comment by EPuncker** [comment]
20121605 for RE, 7 days later for non RE :P

**Comment by MStr3am** [comment]
uh yea whatever -_-
