### ISSUE TITLE
msgstringtable extractor not working

### ISSUE THREAD

**Issue by EPuncker** [MStr3am/NEMO#32]
Loaded 2014-10-22bRagexe and used the extractor thing but it just generates an empty txt file

![2015-05-08 04_25_06-output](https://cloud.githubusercontent.com/assets/4684880/7532175/58a23096-f53a-11e4-9468-977ea736059e.png)

**Comment by reigneil** [comment]
this is also broken using 2014-06-13aRagexe

**Comment by MStr3am** [comment]
found the issue, will fix it.

**Comment by MStr3am** [comment]
have fixed it in local. Will push the changes in today.
