### ISSUE TITLE
Disable 255 attribute points visual limit

### ISSUE THREAD

**Issue by EPuncker** [MStr3am/NEMO#33]
Is it possible to make a diff that take out the limit of displaying only 255 status in the character selection window and display the real value?

**Comment by MStr3am** [comment]
hmm not sure will have to check. i want to close all the issues before i proceed to adding new patches.

**Comment by EPuncker** [comment]
okay :D

**Comment by MStr3am** [comment]
uh aren't stats limited to 255 anyways since the client only uses 1 byte for them?

**Comment by EPuncker** [comment]
in game I use 600 and they display just fine

**Comment by MStr3am** [comment]
the packet sent from Char Server uses 1 byte for each stat which can only hold till 255. 
Its a packet limitation can't do much about it sadly.
Look at packet structs beginning with PACKET_HC_ACCEPT_ to see what i am talking about

**Comment by EPuncker** [comment]
Kinda weird since it seems to display until 32k in-game, but on select char screen (that is were I wanted the patch to work) it doesn't, but since this is not a major thing I guess its fine as is
