### ISSUE TITLE
Skip Service Select issue with langtype 0

### ISSUE THREAD

**Issue by reigneil** [MStr3am/NEMO#34]
@MStr3am is this compatible with langtype 0? i'm using 2015-05-13aRagexe client

**Comment by MStr3am** [comment]
yes why?

**Comment by reigneil** [comment]
because it didn't work. it wont let you select the first service and it will end up cant connect to server but if we use langtype 1 then it can connect... weird isn't it.

**Comment by MStr3am** [comment]
odd i have been using langtype 0 and it works fine for me although i only have 1 connection in my clientinfo.xml
You have selected Always Call SelectKoreaClientInfo() patch right? I was having issue before because that patch was incomplete then.

**Comment by reigneil** [comment]
yes. maybe i'll try to download this again and see if it is working for me also.

**Comment by reigneil** [comment]
it looks like this is may fault. i try and it work... maybe it is something to do with the rollback I made with my patcher. sorry for my mistake... make this as invaild
