### ISSUE TITLE
[font]newline square issue

### ISSUE THREAD

**Issue by reigneil** [MStr3am/NEMO#35]
i'm having this trouble for so long that all text with a new line do have this square character.
![newline](https://cloud.githubusercontent.com/assets/9740000/7686175/7299f558-fdc6-11e4-85e7-7779eea126a4.JPG)

what i do know about this it happen when you do not select langtype 0, that this is a font issue with windows user or do not install korean language? that it didn't read .eot.

can you please tell me how would i eliminate this? or
can we revive this use arial in all langtype that work with langtype 0 before?

**Comment by MStr3am** [comment]
hmm ill look into it

**Comment by MStr3am** [comment]
which langtype are you using?

**Comment by reigneil** [comment]
langtype 1 or 7.

**Comment by MStr3am** [comment]
i tried with langtype 1 but im not seeing the issue

**Comment by MStr3am** [comment]
Closing this since I don't see the issue. In case you are still facing this problem please reopen
