### ISSUE TITLE
Ability to load itemInfo after server selection.

### ISSUE THREAD

**Issue by dastgir** [MStr3am/NEMO#38]
The client should send server name as parameter to the function of iteminfo.
This would facilate using item associated with different server having different description and slots.

**Comment by EPuncker** [comment]
that would rocks

**Comment by MStr3am** [comment]
I have added the patch, see if it works for you. 
The main function will get the server name as the argument when it is loaded upon char selection.
Another point to note - right now each time you do char selection it reloads the iteminfo file (unless the same char server is being used as last time). so it can get slow depending on ur iteminfo

**Comment by MStr3am** [comment]
Report a seperate issue if the patch causes any. Closing this for now.
