### ISSUE TITLE
Ability to execute new lua

### ISSUE THREAD

**Issue by dastgir** [MStr3am/NEMO#39]
Client should execute a lua function(custom function) with server name, and the function will do all The things required.
This can facilate changing of tables of other lua files by directly modifying them from that newly created custom function.

**Comment by dastgir** [comment]
To be called after server selection, and server name to be passed go a custom function.

**Comment by MStr3am** [comment]
uh how is it different from ItemInfo one

**Comment by dastgir** [comment]
Just noticed, nothing new. xD
