### ISSUE TITLE
Ability to execute lua function upon map change

### ISSUE THREAD

**Issue by dastgir** [MStr3am/NEMO#40]
While changing map, a new lua function should be called up with map name.
Current implementation is there (effects of map, you can see in lua files folder)
But that have hardcoded map names, thus we cannot use them.
Adding ability to execute lua function on map change can make it easy to add new effects on map and make it good.

**Comment by dastgir** [comment]
Bump!

**Comment by MStr3am** [comment]
I just added a patch. Now all corresponding map files will get read by the client when it loads maps (file is only read the first time a map is loaded).

Although not sure if this is really showing the effects since I don't understand how the EffectTool lua files are being used.

**Comment by MStr3am** [comment]
closing this for now. if the patch is not working let me know.
