### ISSUE TITLE
Aura above individual Levels [Reminder]

### ISSUE THREAD

**Issue by MStr3am** [MStr3am/NEMO#41]
Check on Aura above Individual Levels.

**Comment by Jedzkie** [comment]
@MStr3am bump this also.

**Comment by Jedzkie** [comment]
If you adding this patch, i suggest also to add also change 3rd job aura, which we can select the blue or yellow aura to be enabled.

**Comment by Jedzkie** [comment]
@MStr3am bump!

**Comment by MStr3am** [comment]
Patch is called 'Use Custom Aura Limits'. Completed and checked in.
