### ISSUE TITLE
Ignore Missing File Error Patch

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#45]
![ignore](https://cloud.githubusercontent.com/assets/4976551/8314682/9c3ee972-1a1d-11e5-87b7-b8fd20fdbabf.jpg)

Client: 2015-05-13

**Comment by MStr3am** [comment]
Yes im working on that one. 
Planning to either make it 
   Ignore only the Resource Error Messages
or 
   Skip showing the Error Message Box  altogether like in current scenario and rename the patch (well some cases would still show them)

**Comment by MStr3am** [comment]
Fixed.
