### ISSUE TITLE
About /who cmmand 

### ISSUE THREAD

**Issue by Angelmelody** [MStr3am/NEMO#46]
Hi @MStr3am ,Would it be possible to add an option EnableWhoOnAllLangtypes which make the /who command work for all Lang types?

**Comment by MStr3am** [comment]
should be possible

**Comment by QQfoolsorellina** [comment]
thanks you
![s7](https://cloud.githubusercontent.com/assets/2773211/8451353/4b762084-2015-11e5-809f-ecb2ab3c5715.png)

**Comment by MStr3am** [comment]
This has been added.

**Comment by QQfoolsorellina** [comment]
@MStr3am 
Thanks, but  It seems not working  with 2014-02-05bRagexe (diffed with enable /who command option)
<img width="768" alt="222" src="https://cloud.githubusercontent.com/assets/2773211/9840376/c28bf9f8-5ac3-11e5-84a6-b4dc5090d66e.png">

**Comment by MStr3am** [comment]
I am able to use it fine. If u still have the error please post a new issue
