### ISSUE TITLE
Always Use Email for Char Deletion

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#48]
![always use](https://cloud.githubusercontent.com/assets/4976551/8707911/41e9f494-2b6b-11e5-8aa5-f1c6ddf9dbb3.jpg)
Client: 2013-08-07aRagexe

**Comment by MStr3am** [comment]
Fixed in Local. Will be added in next update

**Comment by lelouch22** [comment]
Offtopic:
Is it possible you can add a support for Level 255 Aura in 2013 and above clients? or its impossible because of the conflicts on 160 and 175 aura?

**Comment by MStr3am** [comment]
hmm odd its still patching the same area . reason for name change is that it also skips showing other resource related errors hence name change. ill do a comparison and see if i ended up removing something

**Comment by MStr3am** [comment]
can you put the Resource Patch problem as a seperate issue. The Char Email deletion one is fixed now - so i am closing this one.
