### ISSUE TITLE
Ignore Resource Error Patch

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#50]
May i ask is the Ignore Resource Error Patch really working? because after i applied the patch some missing sprites or files keeps popping up but if you use an older version of NEMO there are no missing sprite or files message that will pop up in your screen. Any solution for that issue?

**Comment by MStr3am** [comment]
can you show an example?

**Comment by MStr3am** [comment]
Still waiting for a screenshot / example of when it happens

**Comment by lelouch22** [comment]
![error](https://cloud.githubusercontent.com/assets/4976551/12163093/31beb3de-b545-11e5-87ee-c3e6d5002fb7.jpg)
I already added the Ignore Resource Errors patch

Client: 2015-09-16

**Comment by MStr3am** [comment]
When does this happen?

**Comment by lelouch22** [comment]
That happens when i open the achievement system but i think its normal. Also i think its fixed already because if you view the item without any texture file it doesnt show any missing file message like before.

**Comment by MStr3am** [comment]
oh can i close this then.

**Comment by lelouch22** [comment]
Yup you can close it (but i already closed it :D)
