### ISSUE TITLE
[Request] Hairstyle & Haircolor Cap

### ISSUE THREAD

**Issue by AetherHaziel** [MStr3am/NEMO#51]
I would like a Diff that I may set the hardcode of the cap for both Haircolor and Hairstyles on Character Creation Screen.

**Comment by lelouch22** [comment]
Have you tryed the Enable 64k Hairstyle Patch?

**Comment by MStr3am** [comment]
Patch has been checked in => Increase Hair Style & Color Limits.
Please note that Doram clients are yet to be done.
