### ISSUE TITLE
2012-04-10 + Custom Job 

### ISSUE THREAD

**Issue by HeroGarr** [MStr3am/NEMO#52]
Greetings. Today I've tried to apply Custom Job patch to 2012-04-10 client. So far, by testing it before adding anything new, I found out that I'm getting a client crash every time I try to use a cash mount. I have a client without that patch and flag icons, and cash mounts work fine in there.

**Comment by HeroGarr** [comment]
If needed, I can provide test server access and both patched clients for testing.

**Comment by MStr3am** [comment]
Issue is fixed.
