### ISSUE TITLE
[Suggestion] Disable Map Interface

### ISSUE THREAD

**Issue by Jedzkie** [MStr3am/NEMO#53]
Hi Neo!

Can you add this diff? It will disable the 'ctrl+~' command to view the map, this will help not only me but for those server owners that uses classic mechanics and interfaces. I hope you will implement this. Thanks!

**Comment by Jedzkie** [comment]
@MStr3am bump!

**Comment by MStr3am** [comment]
which client onwards has this feature.

**Comment by Jedzkie** [comment]
Completely disable Ctrl + `

**Comment by MStr3am** [comment]
do u want to disable the map view itself ? or just the shortcut.

**Comment by Jedzkie** [comment]
Disable the map view as well as the shortcut.

**Comment by MStr3am** [comment]
Patch has been checked in.
