### ISSUE TITLE
Character Create not translated in 2012 Clients

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#54]
![no translated](https://cloud.githubusercontent.com/assets/4976551/9836819/5c97050c-5a5a-11e5-99d5-f8da92af2a33.jpg)

Tested on: 2012-04-18, 2012-06-18 and 2012-07-16

[Note]: But when i use ShinsDiffPatcher "ÄÉ¸¯ÅÍ¸¸µé±â" is translated into "Make Character".

**Comment by MStr3am** [comment]
Added to local. Will be available after next push.

**Comment by MStr3am** [comment]
Fixed in latest commit.
