### ISSUE TITLE
Disable Hackshield 2012-04-10 Error

### ISSUE THREAD

**Issue by Litro** [MStr3am/NEMO#55]
after patched 2012-04-10aRageRe.exe with nemo from latest master, the client give me error, 

when i included disable hackshield in diff the patched client ask for aossdk.dll and v3hunt.dll, in the previous rev of nemo it didn't need that 2 dll, after i put all the client requested file i can't open the patched client and error message pop up tell me "this application failed to initialize properly(Oxc0000006)"

**Comment by MStr3am** [comment]
Fixed in latest commit.
