### ISSUE TITLE
Mapeffect plugin

### ISSUE THREAD

**Issue by HeroGarr** [MStr3am/NEMO#56]
Whenever you try to generate mapeffect plugin using addons menu this error pops up:
![mapeffect](https://cloud.githubusercontent.com/assets/10124529/9953573/a9852aea-5dea-11e5-9b1b-9d519390f0da.jpg)

**Comment by MStr3am** [comment]
ah guess i forgot to update that one. will fix that

**Comment by MStr3am** [comment]
Fixed in latest commit.
