### ISSUE TITLE
Enable custom shield does not work Properly

### ISSUE THREAD

**Issue by seifert10** [MStr3am/NEMO#6]
![postarnoforum](https://cloud.githubusercontent.com/assets/8268912/3704493/a61ba94a-1414-11e4-8d07-701442d558e1.png)
Is someone knowns how to fix it, please reveal!

**Comment by seifert10** [comment]
Is this working now?

**Comment by MStr3am** [comment]
its working now. but you need to copy the shieldtable_F file from the support folder. The issue was in there. Dont worry you wont need to change any of your custom shields.

**Comment by BatangKuneho** [comment]
![2525](https://cloud.githubusercontent.com/assets/11084667/11163663/d8706d1a-8b12-11e5-8c3c-42bef07a72e6.jpg)
![5252](https://cloud.githubusercontent.com/assets/11084667/11163664/d87251f2-8b12-11e5-92a1-fac84080b8f5.jpg)
![121213](https://cloud.githubusercontent.com/assets/11084667/11163665/d872ca1a-8b12-11e5-9c40-cb1ec3d9d996.jpg)
![523411](https://cloud.githubusercontent.com/assets/11084667/11163666/d8749192-8b12-11e5-9b0e-cc9f6385aea3.jpg)
![5625252](https://cloud.githubusercontent.com/assets/11084667/11163667/d8745f6a-8b12-11e5-8b13-1ce541c8ff33.jpg)
![Uploading Untitled12121.jpg…]()
@MStr3am igot error on Custom class  i succesfully do the Custom class.. now i got error ..
