### ISSUE TITLE
Black Login Screen

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#61]
Hi Neo,
I got black login screen on langtype 5, 6, 7, 13, 15, 16, 17, 18, 19

and there is no patch for Enable ACSII for all langtype?

**Comment by MStr3am** [comment]
isnt the Enforce Official Login Background patch not working?

Enable ASCII patch is already there

**Comment by kyeme** [comment]
I patched with Enforce Official Login Background, but its not working

About Enable ASCII, I can confirmed this issue: https://github.com/HerculesWS/Hercules/issues/786

**Comment by kyeme** [comment]
Btw I diff 2015-05-13 client, sorry I forgot.

**Comment by kyeme** [comment]
@MStr3am 
I tested on 2013-12-23 and 2015-05-13 client no "Use Ascii on All LangTypes"
![ss1](https://cloud.githubusercontent.com/assets/4656578/10412853/5ba6e7fe-6fc5-11e5-8756-eea035cccb2c.jpg)

**Comment by MStr3am** [comment]
ah there was a small error in _patchlist.qs for the Ascii patch. will fix it in next commit

as for the official login background its working fine for me. Which client date are you getting issue for
and what all patches did u use maybe something is conflicting with it

**Comment by kyeme** [comment]
Here: http://pastebin.com/z10LVyiA

I'm using 2015-05-13

**Comment by MStr3am** [comment]
Check now. should be fixed.

**Comment by kyeme** [comment]
Working perfect! Thank you.
