### ISSUE TITLE
[suggestion] extend map name length

### ISSUE THREAD

**Issue by QQfoolsorellina** [MStr3am/NEMO#63]
Hi @MStr3am ,
I wonder if it would be possible to add a diff option for extending map name length from 
2 bytes to 4 bytes or more? Because instance map name are limited to 8 char words .

**Comment by MStr3am** [comment]
2 bytes? 16 bytes are allocated for the map name. Anyways, the situation is the same as the char name/account id/guild name etc.
There would be too many locations to change in the client that I do not wish to even attempt to find them all. Also there are lot of packets that already keep the 16 bytes that would need changing both at server side & client side.

In short: It maybe possible but I do not have the patience/detemination (which you will need a lot of) to look around for it.
