### ISSUE TITLE
[Fix] for force exit

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#64]
Hi NEMO,
Can you make a patch for:
"Server still recognize your last login" 
![stillrecog](https://cloud.githubusercontent.com/assets/4656578/10416246/f9a9d09e-7040-11e5-9848-ea1b2728657d.jpg)

"Now Logging Out" - @kick or Changesex
![kick or changesex](https://cloud.githubusercontent.com/assets/4656578/10416247/00a9e456-7041-11e5-8d75-62a56ac50537.jpg)

"Someone has Logged in with this ID" -
![someonelogin](https://cloud.githubusercontent.com/assets/4656578/10416248/0a570df8-7041-11e5-91b1-b2c3c66cda55.jpg)

"Server Closed"
![serverclose](https://cloud.githubusercontent.com/assets/4656578/10416859/d4480a40-705a-11e5-9ef3-195b220e1dfa.jpg)

When appears, will not be forced to quit/exit the client? Just like what you did with "incorrect password", when wrong password was entered, the client will not be forced to quit/exit.

Thank you.

**Comment by kyeme** [comment]
and "Your Game Exe is not the latest version"

Thank you.

**Comment by MStr3am** [comment]
Did it ever return to login screen?

**Comment by kyeme** [comment]
It does not go back to login screen. It exits to window.

**Comment by MStr3am** [comment]
yea my point is did it ever return to login screen in any client date?

**Comment by kyeme** [comment]
I tested on 2015-05-13 client. I will try on oldr client

**Comment by Jedzkie** [comment]
older clients will return to login screen, the bug started in client 2010-08-03aRagexeRE.

**Comment by MStr3am** [comment]
To be added in next commit

**Comment by kyeme** [comment]
@MStr3am 
Thanks Nemo! This is a wonderful update! By the way, you forgot to fix the "Your Game Exe is not the latest version" :D

**Comment by kyeme** [comment]
Up  :D

**Comment by MStr3am** [comment]
When does that error occur anyways?

**Comment by Jedzkie** [comment]
@MStr3am i think this is good already, the game file exe error must force close the client so that the player would not spam login attempts.

**Comment by MStr3am** [comment]
OK I am closing it then
