### ISSUE TITLE
2013-08-07 diff option "Skip Guild Member Cheat Check: Failed in Step 1"

### ISSUE THREAD

**Issue by CairoLee** [MStr3am/NEMO#65]
Hi @MStr3am 

Thank you for your job! 
You make Ragnarok World more colorful.

I want to report a BUG about 2013-08-07 client.
My english is not good, so please see the picture. XD

![fxyxie i4f77 gimku 9 e](https://cloud.githubusercontent.com/assets/4458917/10427649/d491973c-711d-11e5-806b-2bad7a2402e6.jpg)

**Comment by MStr3am** [comment]
check now. there were a couple of errors in that patch that i missed.
