### ISSUE TITLE
Enable Monster Tables

### ISSUE THREAD

**Issue by Jedzkie** [MStr3am/NEMO#67]
Enable Monster Table Error in 2010-07-30aRagexeRE, 2010-06-16aRagexeRE works fine.

<a href="http://tinypic.com?ref=6eeo8w" target="_blank"><img src="http://i59.tinypic.com/6eeo8w.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by MStr3am** [comment]
hmm been wondering if the patch is really doing anything, because i seem to be able to use the monstertalktable even without the patch.

**Comment by MStr3am** [comment]
will be fixed in next commit.

**Comment by Jedzkie** [comment]
Thanks!

**Comment by MStr3am** [comment]
Added to Repo
