### ISSUE TITLE
Party Booking

### ISSUE THREAD

**Issue by Jedzkie** [MStr3am/NEMO#68]
Hi Neo! is it possible to remove specific classes in Party Booking menu? i tried to leave blank the msgstring but it seems the client still reads it. Thanks!

**Comment by Jedzkie** [comment]
@MStr3am bump!

**Comment by MStr3am** [comment]
OK So from what I see. The client loops through the names between msgstring ids 1630-1688 and blank names end up as blank list items.

**Comment by Jedzkie** [comment]
Good Idea.

**Comment by MStr3am** [comment]
Which date was the booking introduced? any idea

**Comment by Jedzkie** [comment]
2010-03-02aRagexeRE

**Comment by MStr3am** [comment]
hmm i just looked at 2012 one and there is no drop down list in that. when was that introduced?

**Comment by Jedzkie** [comment]
2010-03-02aRagexeRE :)

**Comment by MStr3am** [comment]
Patch has been checked in.

**Comment by Jedzkie** [comment]
@MStr3am you forgot the classes, i still see 3rd job in class portion.
