### ISSUE TITLE
[Suggestion] Exit to Cancel

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#69]
Hello Nemo,
Can you change the [exit] button to [cancel] when the "skip service selection screen" is not applied?
Like these photos below:
![1](https://cloud.githubusercontent.com/assets/4656578/10776713/c2b188a0-7d4e-11e5-981c-1cb41dd9673a.jpg)
![2](https://cloud.githubusercontent.com/assets/4656578/10776716/c7045720-7d4e-11e5-9966-1b9929844396.jpg)

Our current setting is that when you already choose a server from the service selection screen, you can't pick a server again because there is no [cancel] button.

Thank you!

**Comment by MStr3am** [comment]
where did u get those screenshots?

**Comment by MStr3am** [comment]
OK Got how to fix it. Will be added in next commit.

**Comment by MStr3am** [comment]
This has been added.
