### ISSUE TITLE
Resurrection Button (Token of Siegfried)

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#70]
Hi Nemo, 
Is it possible for you to make a diff for the Resurrection button. As per experience there is no Resurrection button on my choices when I have Token of Siegfried in my inventory inside PvP maps. Based on the reports this can't be fixed thru server side is it possible to fix it thru hexing?

Bug Report:
http://herc.ws/board/tracker/issue-5693-token-on-siegfried/?gopid=8937#entry8937

Video: 
https://youtu.be/qU-Wkpwksno

Thank you.

**Comment by kyeme** [comment]
@MStr3am 
Is this possible?

**Comment by MStr3am** [comment]
I am checking on it.

**Comment by MStr3am** [comment]
From what I have learned the following can be achieved: 

Resurrect button can be shown irrespective of whether map is GVG, PVP etc.

But the auto resurrection mechanism when you die again seconds after resurrecting is still gonna be there - haven't figured how to disable that just yet.

**Comment by kyeme** [comment]
I can use Token of Sieg on PvP maps now @MStr3am :kiss:

**Comment by kyeme** [comment]
Btw @MStr3am  what is this to do list for?
//To do - When on PVP/GVG map the second time u die, the char gets warped to save point anyways.

**Comment by MStr3am** [comment]
you are not getting automatically warped when u die in PvP or GvG map?

**Comment by kyeme** [comment]
Yes if you die twice, and its server side.

**Comment by MStr3am** [comment]
oh thought it was client side xD. OK then i am closing this.
