### ISSUE TITLE
Pre-renewal features

### ISSUE THREAD

**Issue by zackdreaver** [MStr3am/NEMO#72]
Hello sir NEO,
is it possible to add pre-renewal "features" on renewal client, like:
1. Changing MATK stats window from "+" to "~"
http://herc.ws/board/topic/11149-changing-matk-to/
2. Ability to use healing item when on dialog with NPC
(is this server or client side? not sure)

I will add more when i remember them
thanks

**Comment by kyeme** [comment]
@zackdreaver thanks :D

2. it's server side.

**Comment by zackdreaver** [comment]
@kyeme 
which config i need to edit so i can use healing item?

**Comment by kyeme** [comment]
@malufett forgot the fix for pre-renewal http://herc.ws/board/tracker/issue-6527-talking-to-npc/?gopid=25561&st=20#entry25561

I will make report later

**Comment by kyeme** [comment]
Up~ :D

**Comment by MStr3am** [comment]
This will take time to find out . since there are many other issues i need to look into first, its not on my urgent to-do list.

**Comment by MStr3am** [comment]
hmm didnt take as much time as i thought. 
Patch for #2 has been checked in. Use Tilde for Matk.
