### ISSUE TITLE
Unselect Skip License Screen

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#75]
Licence.txt is not showing on login screen with langtype 1 and others. Can you make it possible to all langtype? Thanks.

**Comment by Jedzkie** [comment]
What client?

**Comment by kyeme** [comment]
2015-05-13 @Jedzkie

**Comment by kyeme** [comment]
Hello neo,Im suggesting EnableLicenceScreen (for all langtype)  and mske it posible to rename example licence_pro.txt like you did in iteminfo.lub so it will not conflict on other RO. Thank you

**Comment by CairoLee** [comment]
in my case. only can show the LicenceScreen when langtype is 4 | 6 | 8 | 9 | 12.
client date: 2013-08-07 | 2015-05-13

can you let all langtype can show LicenceScreen? @MStr3am

**Comment by MStr3am** [comment]
Which one do you mean the "Do you agree" screen or the EULA screen?

**Comment by kyeme** [comment]
The EULA screen

![22](https://cloud.githubusercontent.com/assets/4656578/11893603/de322126-a5ac-11e5-886b-8209204fa88b.jpg)

**Comment by CairoLee** [comment]
Yes, like this~ 

![qq20151218-0](https://cloud.githubusercontent.com/assets/4458917/11893488/09aeccc4-a5ac-11e5-9563-2548704c1837.png)

**Comment by MStr3am** [comment]
Rename License File & Always Show License Screen
patches have been added.
