### ISSUE TITLE
Weird problem on Disconnect To Login Window patch

### ISSUE THREAD

**Issue by kyeme** [MStr3am/NEMO#76]
This happens in Centos Server, when I connect to Hercules, (running on Centos) and I encounter "Server still recognizes your last login" the client will crash.

But when I'm using my local machine, (running Hercules on my PC Windows7) I'm not experiencing client crash when I encounter "Server still recognizes your last login".

I don't know what causes this problem on Hercules emulator or on NEMO thats why I wanted to know if you guys are also experiencing this kind of problem.

**Comment by HeroGarr** [comment]
I have this problem on my Win10 laptop as well.

**Comment by kyeme** [comment]
@HeroGarr I'm using windows 7

@MStr3am can you confirm? :D

**Comment by MStr3am** [comment]
i'll check on this.

**Comment by MStr3am** [comment]
Which client is specifically doing this? I didnt get any error.
About the DNS issue that has been fixed now.

**Comment by HeroGarr** [comment]
I got that with 2012-04-10 client. But I got that only when I tried to kick vendor off with return to login screen patch as well (and restore login window, naturally).

**Comment by MStr3am** [comment]
if you were using DNS patch can you try patching again . There was an issue with it, so it could have been from that.

**Comment by HeroGarr** [comment]
Will do. I'll report only tomorrow though. Thanks a lot <3

**Comment by kyeme** [comment]
@MStr3am no more crash master. :D thank you.

**Comment by MStr3am** [comment]
OK Im closing this then.
