### ISSUE TITLE
Increase Attack Display Issue

### ISSUE THREAD

**Issue by lelouch22** [MStr3am/NEMO#77]
w/o Increase Attack Display: Normal damage digits
w/ Increase Attack Display: Damage show only single digit

Client: 2015-05-13aRagexe.

**Comment by MStr3am** [comment]
ugh guess they changed around the stack pointers....again

**Comment by lelouch22** [comment]
Also sometime when attacking there is a chance that the client will crash.

**Comment by CairoLee** [comment]
I have the same problem.

**Comment by MStr3am** [comment]
This has been fixed.
