### ISSUE TITLE
64k hairstyle in new clients

### ISSUE THREAD

**Issue by pengc2010** [MStr3am/NEMO#78]
For new clients (later than 2015-10-01) that have Dorams supported,
the 64k hairstyle is not able to diff.
I know this is not supported in any emulator, so this is more like a reminder for the hairstyle issue.

**Comment by MStr3am** [comment]
Are you talking about the Increase hairstyles upto 32k patch? 
If so, What issue are you facing? (A snapshot would be great) 
Also I didn't see any releases for that date. Did you unpack the client yourself?

If not why would you need 64k hairstyles? 32k itself is absurdly high
.

**Comment by dastgir** [comment]
He might be the lucky one to download before the client was hidden..
Anyways, that client isn't usable without proper adding of new packets.

**Comment by pengc2010** [comment]
I remember it was released on Hercules board, but there is no support for it yet.

Here it is the error message
![20151215094642](https://cloud.githubusercontent.com/assets/5384294/11813697/cad8b99e-a310-11e5-807e-7f39e16914e4.png)

**Comment by MStr3am** [comment]
Well it looks like that client uses different format string (infact hairstyle number is no longer a string). so I need time to figure out where to change the limiting value.

**Comment by RagnarokNova** [comment]
Sup dawg, the string concerned for hairstyle has been changed to "\¸Ó¸®Åë\%s\%s_%s.%s". The method takes into account the Doram class (4218) as well.

**Comment by MStr3am** [comment]
Check now. I have also extended the Hairstyle for Doram Race.

**Comment by RagnarokNova** [comment]
---------------------------
Patch Error
---------------------------
Increase Hair Style & Color Limits : Failed in Step 1 - HairColor comparison missing
---------------------------

64k patch went through fine, but crashes on login. Will test with an account with characters.

**Comment by MStr3am** [comment]
Need a link for that client

**Comment by RagnarokNova** [comment]
One sec, I'll upload it. Just re-tested with a clean version of the client as I was patching it on a half finished one.

**Comment by MStr3am** [comment]
Hair color one is expected as I stated here : https://github.com/MStr3am/NEMO/issues/51
I'll check the other one.

**Comment by RagnarokNova** [comment]
Right. Thanks for the quick response NEO.

**Comment by MStr3am** [comment]
Check now it should be fixed.

**Comment by RagnarokNova** [comment]
That did it. I experienced a crash but this seems to be a crash that occurs when you're a Doram with hairstyle 6+, which is something I can easily avoid.

**Comment by MStr3am** [comment]
OK i am closing this then.
