### ISSUE TITLE
how to showing the replay button?

### ISSUE THREAD

**Issue by CairoLee** [MStr3am/NEMO#79]
Hi @MStr3am 

In the Taiwan RO Client, you can see an replay button On the Login screen，like this:

![1](https://cloud.githubusercontent.com/assets/4458917/11390299/b4686c0a-9383-11e5-9e15-ba0fb02d4393.png)

Can you make an option to let it showing in the all langtype? 
Thankyou, And sorry about my bad english XD

**Comment by CairoLee** [comment]
Taiwan Client's Langtype is 4 
<langtype>4</langtype>

**Comment by kyeme** [comment]
After selecting Replay theres a Login Mode button
![2](https://cloud.githubusercontent.com/assets/4656578/11762283/8bd5bc7e-a11c-11e5-9996-f4e37cf857b8.jpg)

**Comment by CairoLee** [comment]
Thanks @kyeme , I know this.
But in langtype = 3, client will no showing the replay button .
i hope can make the replay button to show when i using langtype = 3.

Sorry for my bad english XD

**Comment by MStr3am** [comment]
Well it doesnt look like the kRO client has it.

**Comment by MStr3am** [comment]
Can you send me the Taiwan RO client. maybe it will give some clue

**Comment by kyeme** [comment]
Uploading~

**Comment by CairoLee** [comment]
Here is Taiwan RO Ragexe.exe files.
if you need the full client, just tell me~ 
And thank you for you great work! @MStr3am 

[RagAll.zip](https://github.com/MStr3am/NEMO/files/67419/RagAll.zip)

**Comment by kyeme** [comment]
Any news master?

**Comment by kyeme** [comment]
Up 😊

**Comment by MStr3am** [comment]
From what I see, the button already exists in kRO client (it is hidden) but instead of the login screen its there in service selection screen (and ofcourse the Replay Window also has a button for returning to Service selection screen) . I can bring them out of hiding.

But if you want it in login screen its gonna be a bigger hurdle which is not something I will take on any time soon.

**Comment by MStr3am** [comment]
Here is a snapshot of how it would look
![replaysnapshot](https://cloud.githubusercontent.com/assets/4068357/12064927/95c1a09a-aff4-11e5-99d5-db7d960517b1.PNG)
![replaysnapshot2](https://cloud.githubusercontent.com/assets/4068357/12064928/95c32226-aff4-11e5-9fc2-a532630c8ebd.PNG)

**Comment by CairoLee** [comment]
Wow! Well done.
Let them show is all my need~ Not important in login screen or service selection screen. 
Thank you again @MStr3am

**Comment by kyeme** [comment]
Thank you!🎊🎉🎉

**Comment by kyeme** [comment]
@MStr3am can we try it? :D

**Comment by MStr3am** [comment]
Well i restored both buttons but the problem now is when i press select server its not going to the proper service selection screen. Either it doesnt show up or it shows up with an empty list.
need time to figure that one out.

**Comment by CairoLee** [comment]
Thank you for your patience to solve the problem , your are very powerful! @MStr3am

**Comment by MStr3am** [comment]
Will checkin this tonight

**Comment by MStr3am** [comment]
checked in. Show Replay Button

**Comment by CairoLee** [comment]
It's work perfect! Thank you to @MStr3am !

**Comment by kyeme** [comment]
Thanks @MStr3am btw do you have a plan to restore it in login screen?
