### ISSUE TITLE
Palettes not working

### ISSUE THREAD

**Issue by EPuncker** [MStr3am/NEMO#8]
I'm using 2014-02-05bRagexe and have been trying this diff since NEMO went out I guess, I've tried different settings (both diff related and pal related and whatever else you may imagine of lol) but I got no success in getting them working at all, I have 700 palettes, but they just don't display ingame, there are some that do work, I've put some samples so you can check out:

not working: http://depositfiles.org/files/ww6j1ya5c
working: http://depositfiles.org/files/qxhf16sex

they used to work with all my old clients and the diff from weediff or whatever it was called lol, but now with a 2014 client diffed by nemo it just don't work with either a or b option (yes, I made sure that every file name and place was correct and etc)

PS: seems like hair color works for some, but dye color not work at all, only the "official" ones (1, 2, 3 etc?) but them it wont change, I don't know what to do, so I'm here to ask for your help and I'm here to provide any info you want, thanks in advance and thanks for this great tool!

**Comment by EPuncker** [comment]
any progress? :D I went back to palette things lately and a friend is working on a tool that create palettes for the community, and I am suggesting him to support the saving of palettes in the format that NEMO supports for the shared thing :+1:

**Comment by MStr3am** [comment]
can you reupload those palette files again. i dunno where i downloaded them to last time.
i will check with them .

**Comment by EPuncker** [comment]
http://depositfiles.org/files/grkzeznf2

**Comment by MStr3am** [comment]
for some reason its not downloading for me. can you try a different host

**Comment by EPuncker** [comment]
so after years I noticed that the guy gave me 700 not working palettes :/ lol nvm this issue
