### ISSUE TITLE
disable some buttons

### ISSUE THREAD

**Issue by mleo1** [MStr3am/NEMO#80]
Hello, Can you add these
http://herc.ws/board/topic/6463-guide-removing-battleground-and-navigation-buttons/
http://herc.ws/board/topic/6758-disabling-cash-shop-button-in-upper-right-corner/

**Comment by mleo1** [comment]
wahaha spam

**Comment by mleo1** [comment]
lol, my title autism

**Comment by MStr3am** [comment]
nav, bg, bank and cash shop
is there any other button to hide?

**Comment by dastgir** [comment]
Achievement/RoDex

**Comment by kyeme** [comment]
Roulette , booking 🤗

**Comment by MStr3am** [comment]
whats the icon bmp for rodex?

**Comment by Jedzkie** [comment]
@MStr3am Mail_1.bmp/Mail_2.bmp/Mail_3.bmp

**Comment by MStr3am** [comment]
uh that name is not there

**Comment by Jedzkie** [comment]
In ro_icon folder

**Comment by MStr3am** [comment]
Rodex wasnt there before the new style buttons right? 
Will be adding this patch tonight.

**Comment by MStr3am** [comment]
Patch has been added.
