### ISSUE TITLE
[Feature request] Shows the current EXP numbers in menu window

### ISSUE THREAD

**Issue by zackdreaver** [MStr3am/NEMO#81]
Is it possible to patch client so its shows the current EXP numbers instead of % bar?

![ragexp2](https://cloud.githubusercontent.com/assets/10024221/11600894/46f2308a-9b02-11e5-9eb2-e8131c202f90.jpg)

or

![ragexp1](https://cloud.githubusercontent.com/assets/10024221/11600887/3bb6ad4a-9b02-11e5-80a2-581cfc8a5401.jpg)

based on this link : 
http://www.castledragmire.com/ragnarok/programs.php

Thanks.

**Comment by MStr3am** [comment]
you know any client dates that work with this one?

**Comment by zackdreaver** [comment]
From that website it stated that he use beta client (wow)
I don't know which newer client that can be patched with this
this is how he made this
http://www.castledragmire.com/ragnarok/externals/tutorial.txt

**Comment by MStr3am** [comment]
ok do u have that client?

**Comment by MStr3am** [comment]
![showexp](https://cloud.githubusercontent.com/assets/4068357/11939006/d73da918-a844-11e5-8533-3bf9d889899d.PNG)

Heres a screenshot of how it looks like now :) . Does it look fine?

**Comment by zackdreaver** [comment]
...wow Neo that awesome....
I think that's already ok to add the number alongside the exp bars
+1 if there any rep here
(Sorry, haven't reply for last post, can't find the client)

**Comment by MStr3am** [comment]
Na didn't need the client after all . Ok time for final touches before i commit it

**Comment by MStr3am** [comment]
Hmm i can change the color if needed what do u think?

**Comment by MStr3am** [comment]
Checked in. Give it a test run,

**Comment by zackdreaver** [comment]
crashed with 2015-05-13aRagexe
I'll try older client

**Comment by zackdreaver** [comment]
No issue with 2013-12-23cRagexe

**Comment by MStr3am** [comment]
ok ill check that.

**Comment by MStr3am** [comment]
Fixed. New clients had 1 extra argument to the TextOut function -_-

**Comment by zackdreaver** [comment]
Nice,
thank you Neo for creating this patch
![screenlocal001](https://cloud.githubusercontent.com/assets/10024221/11959619/eedffc30-a900-11e5-9f0e-c9acd60e474e.jpg)

Btw, Neo....
I'am wondering if there any possible way to fix "position lag" through patching?
I have enabled "DisableNagleAlgorithm" but still got position lag.
