### ISSUE TITLE
Custom Job Patch

### ISSUE THREAD

**Issue by Jedzkie** [MStr3am/NEMO#82]
Hi Neo,

Custom Job Patch is not working in 2010-06-16aRagexeRE, not error during client diffing, but when i start the client it shows like this:

Error:
1.)
<a href="http://tinypic.com?ref=mru5cn" target="_blank"><img src="http://i66.tinypic.com/mru5cn.png" border="0" alt="Image and video hosting by TinyPic"></a>

2.)
<a href="http://tinypic.com?ref=25g6lo3" target="_blank"><img src="http://i67.tinypic.com/25g6lo3.png" border="0" alt="Image and video hosting by TinyPic"></a>

3.)
<a href="http://tinypic.com?ref=e8wf8n" target="_blank"><img src="http://i63.tinypic.com/e8wf8n.png" border="0" alt="Image and video hosting by TinyPic"></a>

4.)
<a href="http://tinypic.com?ref=20sgb9l" target="_blank"><img src="http://i63.tinypic.com/20sgb9l.png" border="0" alt="Image and video hosting by TinyPic"></a>

5.)
<a href="http://tinypic.com?ref=2ec3l2o" target="_blank"><img src="http://i63.tinypic.com/2ec3l2o.png" border="0" alt="Image and video hosting by TinyPic"></a>

6.)
<a href="http://tinypic.com?ref=o9ldzs" target="_blank"><img src="http://i64.tinypic.com/o9ldzs.png" border="0" alt="Image and video hosting by TinyPic"></a>

Thanks!

**Comment by dastgir** [comment]
Add this to your grf: https://github.com/MStr3am/NEMO/tree/master/Support/Luafiles514/Lua%20Files

**Comment by Jedzkie** [comment]
@dastgir already do that but the No.6 error still shows.

**Comment by Jedzkie** [comment]
@MStr3am Please help xD

**Comment by MStr3am** [comment]
pcJobTbl was the table name used initially when i added the patch in xDiffgen, After adding the patch in NEMO this was changed to PCJobTable. and the old name is no longer referenced anywhere anymore.

So only reason you would be seeing this is if you are using the old lua files instead of the one from support folder like what Dastgir said. 

But since you said you are using the new ones then maybe the old files are still present in some GRF or Data folder that are getting read instead of the new files.

**Comment by Jedzkie** [comment]
@MStr3am I've already changed my grf into new one, the pcjobtbl error is gone but the no.6 error still shows and prevent the client to execute.

**Comment by dastgir** [comment]
There may be error prior to that, that would show file name or at least line, can you show screenshot of all errors currently?

**Comment by Jedzkie** [comment]
Hmmm.. No more errors in lub side, only error left is no.6 image

**Comment by MStr3am** [comment]
that one is odd

**Comment by Jedzkie** [comment]
@MStr3am pls check this thanks!

**Comment by Jedzkie** [comment]
@MStr3am bump?

**Comment by MStr3am** [comment]
Ok i am also seeing the error. it looks like one of the functions has an extra arg push in old clients ugh.
anyways im looking into it.

**Comment by MStr3am** [comment]
This has been fixed. Although I saw some other date showing an error when patching so I need to check that one.
