### ISSUE TITLE
Enable DNS Support - will make 2015-05-13 client crash

### ISSUE THREAD

**Issue by CairoLee** [MStr3am/NEMO#83]
Hi @MStr3am  

I try to use NEMO to diff 2015-05-13 client.
if I selected "Enable DNS Support", then it will make the client crash when connect some IP address.

here is my profile:
[2015-05-13-Diff-Profiles.zip](https://github.com/MStr3am/NEMO/files/55057/2015-05-13-Diff-Profiles.zip)

please edit you clientinfo.xml, and change the address to 60.169.80.183, like this:

```
<clientinfo>
	<servicetype>china</servicetype>
	<servertype>primary</servertype>
	<extendedslot>2</extendedslot>
	<connection>
		<display>[Test] rAthenaCN - Test Server</display>
		<balloon></balloon>
		<address>60.169.80.183</address>
		<port>6900</port>
		<version>52</version>
		<langtype>3</langtype>
		<aid>
		<admin>2000000</admin>
		</aid>
		<registrationweb>http://rathena.cn</registrationweb>
	</connection>
</clientinfo>
```

Whether or not able to connect on 60.169.80.183, the client will be crash when login. 
Notice: connect to 127.0.0.1 can't triggering this problem.

And if unselected "Enable DNS Support", then the client is work very well. 

Can you fix this please? XD  and Sorry for my Bad english.

**Comment by MStr3am** [comment]
Fixed in local. Will be added in next commit.

**Comment by CairoLee** [comment]
Cool, Thank you @MStr3am

**Comment by MStr3am** [comment]
Patch has been added

**Comment by CairoLee** [comment]
@MStr3am work perfect! Thank you XD
