### ISSUE TITLE
Disable GameGuard

### ISSUE THREAD

**Issue by dastgir** [MStr3am/NEMO#84]
For new mains client

**Comment by MStr3am** [comment]
:8ball: "describe" new xD

**Comment by dastgir** [comment]
For clients >= 2015-07-01Ragexe, I can pass the client if you have deleted previous one

**Comment by MStr3am** [comment]
I have 2015-09 and 10 ragexe i think . will check this out.

**Comment by Jedzkie** [comment]
Any news @MStr3am ?

**Comment by MStr3am** [comment]
Patch has been Fixed.
