### ISSUE TITLE
Custom DLL patch

### ISSUE THREAD

**Issue by Samuel23** [MStr3am/NEMO#88]
Using 2014-10-22 client, adding splash dll doesn't load the client.

Splash will be loaded but after, client will crush

**Comment by MStr3am** [comment]
Its not an issue from NEMO. The import tables from that client onwards is really messed up after unpacking and apparently there is some packer code remaining that doesnt load the table with proper addresses when we inject a dll. Unfortunately I do not know how to fix it atm.
