### ISSUE TITLE
Add Color attack, name and healing

### ISSUE THREAD

**Issue by xBeret** [MStr3am/NEMO#89]
Neo would be possible add to NEMO to allow change of colors in attack, name, and healing?

Color Name:
![Color Name](https://lh3.googleusercontent.com/_tSSG38axQeg/TWRm36L_VrI/AAAAAAAAAlc/DHMc-iw-sHU/s800/damagekun.png)

Color healing:

![Color healing](http://i47.tinypic.com/oanh91.jpg)

**Comment by MStr3am** [comment]
Those are private patches. Not going to add them to public release anytime soon.
