### ISSUE TITLE
64K Hairstyles on 2015-10-29a

### ISSUE THREAD

**Issue by RagnarokNova** [MStr3am/NEMO#90]
Though the feature is mostly working in-game, if you select Human during character creation and scroll to a hair above the range of Doram hairs (6), then swap to a Doram, the client will stop responding. I've tried making fake heads for Dorams thinking it might just be that it's calling an out of bound number head, but even that didn't work.

**Comment by RagnarokNova** [comment]
The strangest part is that some out of bounds hairs into Doram don't crash (The female long spiky blue one for example)

**Comment by MStr3am** [comment]
Try it now I fixed a bug that was causing issue in previous clients . Maybe it got fixed?

**Comment by RagnarokNova** [comment]
Still crashes.

**Comment by Emistry** [comment]
it seem like it's now broken for 2014-10-22 client too. previous version of nemo does work to apply this patch.

**Comment by MStr3am** [comment]
Emistry what issue are you seeing.

**Comment by Emistry** [comment]
I remember this patch work in 2014-10-22 client in previous version of NEMO v2.0. but now it doesnt work in NEMO 2.5.

![capture](https://cloud.githubusercontent.com/assets/1075099/12071035/56895c8c-b0d1-11e5-8239-443fa4568b2a.PNG)

**Comment by MStr3am** [comment]
eh its working fine for me for that date. did u update NEMO? this issue was there before as referred in https://github.com/MStr3am/NEMO/issues/91

**Comment by Emistry** [comment]
I am currently using f8e078b14d1ba07e2935b52c1c14ee8e3f64230f maybe i will try checkout a new copy again later, thx for the info :D

**Comment by RagnarokNova** [comment]
Were you able to confirm the issue that I was having Neo? Not sure if your previous comment was exclusively referring to Emistry.

**Comment by MStr3am** [comment]
yes I was able to confirm your issue and I have made a fix for it. But now I am wondering whether if i should keep the Doram limit as is since we dont really have custom Doram hairstyles yet.

**Comment by RagnarokNova** [comment]
If it's not too difficult maybe add both options as two separate patches? I can imagine someone could maybe want to use the human heads on the cat sprites (Not me haha.)

**Comment by RagnarokNova** [comment]
And any chance we could get your current fix for now? <3

**Comment by MStr3am** [comment]
Na I don't want to split this into two patches. I'll checkin with the limit removal not applied for doram for the time being.

**Comment by MStr3am** [comment]
checked in.

**Comment by RagnarokNova** [comment]
Working great, thanks a ton Neo!
