### ISSUE TITLE
custom window title 2015

### ISSUE THREAD

**Issue by joelolopez** [MStr3am/NEMO#98]
not working, even though you already put your custom window title, the output is still "Ragnarok" 20150916

**Comment by MStr3am** [comment]
Uh its working for me. What did you try to change it to?

**Comment by RagnarokNova** [comment]
Working just fine for me as well.

**Comment by secretdataz** [comment]
Uh, no, doesn't work here. Tested with Ragexe 2015-11-04a and recommended patches.
![image](https://cloud.githubusercontent.com/assets/2021243/12167144/fba0e5c0-b55c-11e5-9af0-fe91b6a93584.png)

**Comment by joelolopez** [comment]
i use 20150916aragexe is still not working i swear <img src="https://z-1-scontent-sea1-1.xx.fbcdn.net/hphotos-xap1/v/t34.0-0/p206x206/12476223_10204268801560121_690152391_n.jpg?oh=6981620a06dfd4b39871848c1835e20e&oe=5690B25F" height=480 width=640>

**Comment by MStr3am** [comment]
which langtype are you using maybe kRO added some langtype specific title change.

**Comment by joelolopez** [comment]
lang type 9

**Comment by MStr3am** [comment]
ill check with that

**Comment by CairoLee** [comment]
@joelolopez I think you need upload you Exe and your profile (2 Exe, before diff and after diff). Maybe your exe has problem.

**Comment by joelolopez** [comment]
i downloaded the ragexe from here mega:///#!8pQzwSwD!CyeyYi0PwZLNg3rlUu_3IFlZTbDpKr43E3Zs_slWdHE

and im not using unsupported patches

where should i get undiff clients?

**Comment by MStr3am** [comment]
oO how do i download from that.

**Comment by secretdataz** [comment]
Here you go.
https://mega.nz/#!8pQzwSwD!CyeyYi0PwZLNg3rlUu_3IFlZTbDpKr43E3Zs_slWdHE

**Comment by joelolopez** [comment]
@MStr3am select download through your browser

**Comment by joelolopez** [comment]
@MStr3am sir where did u get your 20150916 , i would like to use your 20150916 client to test the custom title window

**Comment by MStr3am** [comment]
i was using RE clients from that onwards. it looks like main client has a langtype based title selection now.

**Comment by MStr3am** [comment]
Try now. issue has been fixed.
